#!/bin/sh

INSTALL_LIBS=/root/install_python_libs.py
FLASK_APP=/root/flask_server/app.py
GPS_DAEMON=/root/gps-daemon.py
FLASK_ENV=production
HOST=0.0.0.0
PORT=80
date 010100002025.00
rdate -s time.bora.net
python3 $INSTALL_LIBS
python3 $GPS_DAEMON &
python3 $FLASK_APP &
exit 0

